version: '3'

services:
  imedia24-backend:
    build:
      context: ../imedia24-backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ../imedia24-backend:/app
    environment:
      NODE_ENV: development

  imedia24-frontend:
    build:
      context: ../imedia24-frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ../imedia24-frontend:/app
    environment:
      NODE_ENV: development
